In [1]:
import numpy as np

In [4]:
np.__version__

'1.15.1'

## Python list

In [5]:
li = list(range(10))
li

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
li[5] = 'hello Python'

In [7]:
li

[0, 1, 2, 3, 4, 'hello Python', 6, 7, 8, 9]

## Python array

In [8]:
import array 
arr = array.array('i',list(range(10)))
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr[5] = 'hello Python'

TypeError: an integer is required (got type str)

In [10]:
arr[5] = 78
arr

array('i', [0, 1, 2, 3, 4, 78, 6, 7, 8, 9])

## numpy.ndarray

In [11]:
nparr = np.array(list(range(10)))
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
type(nparr)

numpy.ndarray

In [13]:
nparr.dtype

dtype('int64')

In [14]:
nparr[3] = 33

In [15]:
nparr

array([ 0,  1,  2, 33,  4,  5,  6,  7,  8,  9])

In [16]:
nparr[3]

33

In [17]:
nparr[5] = 'hello Python'

ValueError: invalid literal for int() with base 10: 'hello Python'

In [20]:
nparr[5] = 55.78  # 整数类型的ndarray，放入小数，截取小数点前整数

In [21]:
nparr

array([ 0,  1,  2, 33,  4, 55,  6,  7,  8,  9])

In [22]:
nparr2 = np.array([1, 2, 3.0])

In [23]:
nparr2.dtype

dtype('float64')

In [24]:
nparr3 = np.array([1, 2, 3], dtype=float)

In [25]:
nparr3

array([1., 2., 3.])

## 1 方便处理多维度数组或者矩阵之间的运算
## 2 在处理多维数组或者矩阵，运算效率高

In [28]:
def python_test(n):
    a = [i**2 for i in range(n)]
    b = [i**3 for i in range(n)]
    c = []
    for i in range(n):
        c.append(a[i] + b[i]
    return c
python_test(10)

[0, 2, 12, 36, 80, 150, 252, 392, 576, 810]

In [29]:
def numpy_test(n):
    a = np.arange(n) ** 2
    b = np.arange(n) ** 3
    c = a + b
    return c
numpy_test(10)

array([  0,   2,  12,  36,  80, 150, 252, 392, 576, 810])

In [30]:
%time res = python_test(10000000)


CPU times: user 13.9 s, sys: 1.44 s, total: 15.4 s
Wall time: 17.9 s


In [31]:
%time res = numpy_test(10000000)

CPU times: user 336 ms, sys: 285 ms, total: 621 ms
Wall time: 802 ms


## 矩阵和随机数的生成

In [32]:
np.array([1, 2, 3])

array([1, 2, 3])

In [33]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(2, 20, 3)

array([ 2,  5,  8, 11, 14, 17])

In [36]:
np.arange(2, 20, 0.3)

array([ 2. ,  2.3,  2.6,  2.9,  3.2,  3.5,  3.8,  4.1,  4.4,  4.7,  5. ,
        5.3,  5.6,  5.9,  6.2,  6.5,  6.8,  7.1,  7.4,  7.7,  8. ,  8.3,
        8.6,  8.9,  9.2,  9.5,  9.8, 10.1, 10.4, 10.7, 11. , 11.3, 11.6,
       11.9, 12.2, 12.5, 12.8, 13.1, 13.4, 13.7, 14. , 14.3, 14.6, 14.9,
       15.2, 15.5, 15.8, 16.1, 16.4, 16.7, 17. , 17.3, 17.6, 17.9, 18.2,
       18.5, 18.8, 19.1, 19.4, 19.7])

In [37]:
# np.zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [38]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [39]:
# shape 
np.zeros(shape = (3, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [40]:
# np.ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [41]:
np.ones(shape = (3, 5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [42]:
# np.full
np.full(10, 99)

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [47]:
np.full((3, 5), 99)

array([[99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99]])

In [48]:
# 等差数列
np.linspace(0, 20, 10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

## 生成随机数

In [53]:
np.random.randint(0, 10)

3

In [54]:
np.random.randint(0, 10, size = 5)

array([8, 1, 0, 6, 4])

In [55]:
np.random.randint(0, 10, size = (2, 5))

array([[6, 8, 2, 3, 4],
       [2, 8, 0, 8, 2]])

In [66]:
np.random.seed(100)
np.random.randint(1, 10, 5)

array([9, 9, 4, 8, 8])

In [67]:
np.random.random() # 0到1 的浮点数

0.5263824674842963

In [68]:
np.random.random((3, 5)) # 0到1 的浮点数

array([[0.14860484, 0.15671108, 0.18646718, 0.21010774, 0.4527399 ],
       [0.87014264, 0.06368104, 0.62431189, 0.52334774, 0.56229626],
       [0.00581719, 0.30742321, 0.95018431, 0.12665424, 0.07898787]])

## ndarray基础操作

In [69]:
A = np.ones(shape = (3, 5))
A

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [70]:
A.ndim

2

In [71]:
A.shape

(3, 5)

In [72]:
A.size

15

In [74]:
# reshape 修改维度
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
X = a.reshape(2, 5)
X

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [76]:
X = a.reshape(2, -1)
X

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [77]:
X = a.reshape(-1, 2)
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

## 取值操作

In [78]:
X = np.arange(15).reshape(3, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [79]:
X[0]

array([0, 1, 2, 3, 4])

In [80]:
X[-1]

array([10, 11, 12, 13, 14])

In [81]:
X[0][1]    # 不推荐

1

In [82]:
X[(0, 1)]

1

In [83]:
X[0, 1]

1

## 切片

In [85]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
a[0:5]

array([0, 1, 2, 3, 4])

In [87]:
a[:5]

array([0, 1, 2, 3, 4])

In [88]:
a[5:]

array([5, 6, 7, 8, 9])

In [89]:
a[0:8:2]

array([0, 2, 4, 6])

In [90]:
a[::2]

array([0, 2, 4, 6, 8])

In [91]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## 二维数组的切片操作

In [92]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [93]:
# 前3列，前2行
X[0:2, 0:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [94]:
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [95]:
X[:2][:3] # 前2行，再取前3行

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [96]:
X[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [97]:
X[::-1,::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [100]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [101]:
X.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

## 矩阵的合并

In [102]:
X1 = np.array([[22, 168],
               [18,187]])

In [103]:
X2 = np.array([[0],
               [1]])

In [104]:
X = np.concatenate([X1, X2], axis = 1)
X

array([[ 22, 168,   0],
       [ 18, 187,   1]])

## 聚合操作

In [107]:
X = np.arange(15).reshape(3, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [108]:
np.sum(X)

105

In [109]:
np.max(X)

14

In [110]:
np.mean(X)

7.0